spring.application.name=smart-pay-platform

# MySQL connectivity to Local
spring.datasource.url=jdbc:mysql://localhost:3306/smart_pay_platform
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MySQL credentials
spring.datasource.username=root
spring.datasource.password=password


# JPA & Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# Application running platform
spring.port=8080